/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MessageType = IDL.Variant({
  'text' : IDL.Null,
  'document' : IDL.Null,
  'image' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Status = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'title' : IDL.Text,
  'assignedBy' : IDL.Principal,
  'assignedTo' : IDL.Principal,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'dropLocation' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const LogEntry = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const Status__1 = IDL.Variant({
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const Role = IDL.Variant({
  'owner' : IDL.Null,
  'worker' : IDL.Null,
  'driver' : IDL.Null,
});
export const Profile = IDL.Record({
  'id' : IDL.Text,
  'status' : Status__1,
  'name' : IDL.Text,
  'role' : Role,
  'lastSeen' : IDL.Int,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'messageType' : MessageType,
  'timestamp' : IDL.Int,
  'receiver' : IDL.Principal,
  'fileUrl' : IDL.Opt(ExternalBlob),
});
export const Location = IDL.Record({
  'latitude' : IDL.Int,
  'isSharing' : IDL.Bool,
  'longitude' : IDL.Int,
  'timestamp' : IDL.Int,
});
export const RegisterUserInput = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'broadcastMessage' : IDL.Func(
      [IDL.Vec(IDL.Principal), IDL.Text, MessageType, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'createTask' : IDL.Func([Task], [IDL.Text], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'getActiveWorkerCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFiles' : IDL.Func([MessageType], [IDL.Vec(Message)], ['query']),
  'getMessagesWithUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
  'getTaskStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total' : IDL.Nat,
          'pending' : IDL.Nat,
          'completed' : IDL.Nat,
          'inProgress' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUser' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'getUserLocation' : IDL.Func([IDL.Principal], [Location], ['query']),
  'getUserLogs' : IDL.Func([IDL.Principal], [IDL.Vec(LogEntry)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func([RegisterUserInput], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, MessageType, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'toggleLocationSharing' : IDL.Func([IDL.Bool], [], []),
  'updateMyLocation' : IDL.Func([IDL.Int, IDL.Int], [], []),
  'updateMyStatus' : IDL.Func([Status__1], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Text, Status], [], []),
  'uploadFile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MessageType = IDL.Variant({
    'text' : IDL.Null,
    'document' : IDL.Null,
    'image' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Status = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'title' : IDL.Text,
    'assignedBy' : IDL.Principal,
    'assignedTo' : IDL.Principal,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'dropLocation' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const LogEntry = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const Status__1 = IDL.Variant({ 'offline' : IDL.Null, 'online' : IDL.Null });
  const Role = IDL.Variant({
    'owner' : IDL.Null,
    'worker' : IDL.Null,
    'driver' : IDL.Null,
  });
  const Profile = IDL.Record({
    'id' : IDL.Text,
    'status' : Status__1,
    'name' : IDL.Text,
    'role' : Role,
    'lastSeen' : IDL.Int,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'messageType' : MessageType,
    'timestamp' : IDL.Int,
    'receiver' : IDL.Principal,
    'fileUrl' : IDL.Opt(ExternalBlob),
  });
  const Location = IDL.Record({
    'latitude' : IDL.Int,
    'isSharing' : IDL.Bool,
    'longitude' : IDL.Int,
    'timestamp' : IDL.Int,
  });
  const RegisterUserInput = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLog' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'broadcastMessage' : IDL.Func(
        [IDL.Vec(IDL.Principal), IDL.Text, MessageType, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'createTask' : IDL.Func([Task], [IDL.Text], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'getActiveWorkerCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllLogs' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFiles' : IDL.Func([MessageType], [IDL.Vec(Message)], ['query']),
    'getMessagesWithUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTask' : IDL.Func([IDL.Text], [Task], ['query']),
    'getTaskStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total' : IDL.Nat,
            'pending' : IDL.Nat,
            'completed' : IDL.Nat,
            'inProgress' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUser' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'getUserLocation' : IDL.Func([IDL.Principal], [Location], ['query']),
    'getUserLogs' : IDL.Func([IDL.Principal], [IDL.Vec(LogEntry)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func([RegisterUserInput], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, MessageType, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'toggleLocationSharing' : IDL.Func([IDL.Bool], [], []),
    'updateMyLocation' : IDL.Func([IDL.Int, IDL.Int], [], []),
    'updateMyStatus' : IDL.Func([Status__1], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Text, Status], [], []),
    'uploadFile' : IDL.Func([IDL.Text, IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };