/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Location {
  'latitude' : bigint,
  'isSharing' : boolean,
  'longitude' : bigint,
  'timestamp' : bigint,
}
export interface LogEntry {
  'id' : string,
  'action' : string,
  'userId' : Principal,
  'timestamp' : bigint,
  'details' : string,
}
export interface Message {
  'id' : string,
  'content' : string,
  'sender' : Principal,
  'messageType' : MessageType,
  'timestamp' : bigint,
  'receiver' : Principal,
  'fileUrl' : [] | [ExternalBlob],
}
export type MessageType = { 'text' : null } |
  { 'document' : null } |
  { 'image' : null };
export interface Profile {
  'id' : string,
  'status' : Status__1,
  'name' : string,
  'role' : Role,
  'lastSeen' : bigint,
}
export interface RegisterUserInput {
  'id' : string,
  'name' : string,
  'role' : Role,
}
export type Role = { 'owner' : null } |
  { 'worker' : null } |
  { 'driver' : null };
export type Status = { 'pending' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export type Status__1 = { 'offline' : null } |
  { 'online' : null };
export interface Task {
  'id' : string,
  'status' : Status,
  'title' : string,
  'assignedBy' : Principal,
  'assignedTo' : Principal,
  'date' : bigint,
  'description' : string,
  'dropLocation' : string,
  'pickupLocation' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLog' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'broadcastMessage' : ActorMethod<
    [Array<Principal>, string, MessageType, [] | [ExternalBlob]],
    undefined
  >,
  'createTask' : ActorMethod<[Task], string>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'getActiveWorkerCount' : ActorMethod<[], bigint>,
  'getAllLogs' : ActorMethod<[], Array<LogEntry>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFiles' : ActorMethod<[MessageType], Array<Message>>,
  'getMessagesWithUser' : ActorMethod<[Principal], Array<Message>>,
  'getMyTasks' : ActorMethod<[], Array<Task>>,
  'getTask' : ActorMethod<[string], Task>,
  'getTaskStats' : ActorMethod<
    [],
    {
      'total' : bigint,
      'pending' : bigint,
      'completed' : bigint,
      'inProgress' : bigint,
    }
  >,
  'getUser' : ActorMethod<[Principal], Profile>,
  'getUserLocation' : ActorMethod<[Principal], Location>,
  'getUserLogs' : ActorMethod<[Principal], Array<LogEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<[RegisterUserInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'sendMessage' : ActorMethod<
    [Principal, string, MessageType, [] | [ExternalBlob]],
    undefined
  >,
  'toggleLocationSharing' : ActorMethod<[boolean], undefined>,
  'updateMyLocation' : ActorMethod<[bigint, bigint], undefined>,
  'updateMyStatus' : ActorMethod<[Status__1], undefined>,
  'updateTaskStatus' : ActorMethod<[string, Status], undefined>,
  'uploadFile' : ActorMethod<[string, string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];