/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    latitude: bigint;
    isSharing: boolean;
    longitude: bigint;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Task {
    id: string;
    status: Status;
    title: string;
    assignedBy: Principal;
    assignedTo: Principal;
    date: bigint;
    description: string;
    dropLocation: string;
    pickupLocation: string;
}
export interface Profile {
    id: string;
    status: Status__1;
    name: string;
    role: Role;
    lastSeen: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RegisterUserInput {
    id: string;
    name: string;
    role: Role;
}
export interface LogEntry {
    id: string;
    action: string;
    userId: Principal;
    timestamp: bigint;
    details: string;
}
export interface Message {
    id: string;
    content: string;
    sender: Principal;
    messageType: MessageType;
    timestamp: bigint;
    receiver: Principal;
    fileUrl?: ExternalBlob;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum MessageType {
    text = "text",
    document_ = "document",
    image = "image"
}
export enum Role {
    owner = "owner",
    worker = "worker",
    driver = "driver"
}
export enum Status {
    pending = "pending",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted",
    inProgress = "inProgress"
}
export enum Status__1 {
    offline = "offline",
    online = "online"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addLog(action: string, details: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    broadcastMessage(receivers: Array<Principal>, content: string, messageType: MessageType, fileUrl: ExternalBlob | null): Promise<void>;
    createTask(taskInput: Task): Promise<string>;
    deleteFile(fileId: string): Promise<void>;
    getActiveWorkerCount(): Promise<bigint>;
    getAllLogs(): Promise<Array<LogEntry>>;
    getAllTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<Profile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFiles(fileType: MessageType): Promise<Array<Message>>;
    getMessagesWithUser(user: Principal): Promise<Array<Message>>;
    getMyTasks(): Promise<Array<Task>>;
    getTask(taskId: string): Promise<Task>;
    getTaskStats(): Promise<{
        total: bigint;
        pending: bigint;
        completed: bigint;
        inProgress: bigint;
    }>;
    getUser(user: Principal): Promise<Profile>;
    getUserLocation(user: Principal): Promise<Location>;
    getUserLogs(user: Principal): Promise<Array<LogEntry>>;
    getUserProfile(user: Principal): Promise<Profile | null>;
    isCallerAdmin(): Promise<boolean>;
    registerUser(user: RegisterUserInput): Promise<void>;
    saveCallerUserProfile(profile: Profile): Promise<void>;
    sendMessage(receiver: Principal, content: string, messageType: MessageType, fileUrl: ExternalBlob | null): Promise<void>;
    toggleLocationSharing(isSharing: boolean): Promise<void>;
    updateMyLocation(latitude: bigint, longitude: bigint): Promise<void>;
    updateMyStatus(status: Status__1): Promise<void>;
    updateTaskStatus(taskId: string, newStatus: Status): Promise<void>;
    uploadFile(name: string, fileType: string, fileReference: ExternalBlob): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, Message as _Message, MessageType as _MessageType, Profile as _Profile, RegisterUserInput as _RegisterUserInput, Role as _Role, Status as _Status, Status__1 as _Status__1, Task as _Task, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addLog(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLog(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async broadcastMessage(arg0: Array<Principal>, arg1: string, arg2: MessageType, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.broadcastMessage(arg0, arg1, to_candid_MessageType_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.broadcastMessage(arg0, arg1, to_candid_MessageType_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createTask(arg0: Task): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(to_candid_Task_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(to_candid_Task_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async getActiveWorkerCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveWorkerCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveWorkerCount();
            return result;
        }
    }
    async getAllLogs(): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLogs();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFiles(arg0: MessageType): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFiles(to_candid_MessageType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFiles(to_candid_MessageType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesWithUser(arg0: Principal): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesWithUser(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesWithUser(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTasks();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTasks();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTask(arg0: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_Task_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_Task_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskStats(): Promise<{
        total: bigint;
        pending: bigint;
        completed: bigint;
        inProgress: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskStats();
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<Profile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_Profile_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_Profile_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserLocation(arg0: Principal): Promise<Location> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLocation(arg0);
            return result;
        }
    }
    async getUserLogs(arg0: Principal): Promise<Array<LogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLogs(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<Profile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerUser(arg0: RegisterUserInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterUserInput_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterUserInput_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: Profile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_Profile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: MessageType, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, to_candid_MessageType_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, to_candid_MessageType_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n12(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async toggleLocationSharing(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLocationSharing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLocationSharing(arg0);
            return result;
        }
    }
    async updateMyLocation(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyLocation(arg0, arg1);
            return result;
        }
    }
    async updateMyStatus(arg0: Status__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyStatus(to_candid_Status__1_n45(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyStatus(to_candid_Status__1_n45(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateTaskStatus(arg0: string, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTaskStatus(arg0, to_candid_Status_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTaskStatus(arg0, to_candid_Status_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadFile(arg0: string, arg1: string, arg2: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, arg1, await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MessageType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageType): MessageType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_Message_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Promise<Message> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Profile]): Profile | null {
    return value.length === 0 ? null : from_candid_Profile_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    title: string;
    assignedBy: Principal;
    assignedTo: Principal;
    date: bigint;
    description: string;
    dropLocation: string;
    pickupLocation: string;
}): {
    id: string;
    status: Status;
    title: string;
    assignedBy: Principal;
    assignedTo: Principal;
    date: bigint;
    description: string;
    dropLocation: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedBy: value.assignedBy,
        assignedTo: value.assignedTo,
        date: value.date,
        description: value.description,
        dropLocation: value.dropLocation,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status__1;
    name: string;
    role: _Role;
    lastSeen: bigint;
}): {
    id: string;
    status: Status__1;
    name: string;
    role: Role;
    lastSeen: bigint;
} {
    return {
        id: value.id,
        status: from_candid_Status__1_n26(_uploadFile, _downloadFile, value.status),
        name: value.name,
        role: from_candid_Role_n28(_uploadFile, _downloadFile, value.role),
        lastSeen: value.lastSeen
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    content: string;
    sender: Principal;
    messageType: _MessageType;
    timestamp: bigint;
    receiver: Principal;
    fileUrl: [] | [_ExternalBlob];
}): Promise<{
    id: string;
    content: string;
    sender: Principal;
    messageType: MessageType;
    timestamp: bigint;
    receiver: Principal;
    fileUrl?: ExternalBlob;
}> {
    return {
        id: value.id,
        content: value.content,
        sender: value.sender,
        messageType: from_candid_MessageType_n35(_uploadFile, _downloadFile, value.messageType),
        timestamp: value.timestamp,
        receiver: value.receiver,
        fileUrl: record_opt_to_undefined(await from_candid_opt_n37(_uploadFile, _downloadFile, value.fileUrl))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): Status {
    return "pending" in value ? Status.pending : "completed" in value ? Status.completed : "rejected" in value ? Status.rejected : "accepted" in value ? Status.accepted : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    offline: null;
} | {
    online: null;
}): Status__1 {
    return "offline" in value ? Status__1.offline : "online" in value ? Status__1.online : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: null;
} | {
    worker: null;
} | {
    driver: null;
}): Role {
    return "owner" in value ? Role.owner : "worker" in value ? Role.worker : "driver" in value ? Role.driver : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    document: null;
} | {
    image: null;
}): MessageType {
    return "text" in value ? MessageType.text : "document" in value ? MessageType.document : "image" in value ? MessageType.image : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n19(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Promise<Array<Message>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Message_n33(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MessageType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): _MessageType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterUserInput_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterUserInput): _RegisterUserInput {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status;
    title: string;
    assignedBy: Principal;
    assignedTo: Principal;
    date: bigint;
    description: string;
    dropLocation: string;
    pickupLocation: string;
}): {
    id: string;
    status: _Status;
    title: string;
    assignedBy: Principal;
    assignedTo: Principal;
    date: bigint;
    description: string;
    dropLocation: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: to_candid_Status_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedBy: value.assignedBy,
        assignedTo: value.assignedTo,
        date: value.date,
        description: value.description,
        dropLocation: value.dropLocation,
        pickupLocation: value.pickupLocation
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    role: Role;
}): {
    id: string;
    name: string;
    role: _Role;
} {
    return {
        id: value.id,
        name: value.name,
        role: to_candid_Role_n41(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status__1;
    name: string;
    role: Role;
    lastSeen: bigint;
}): {
    id: string;
    status: _Status__1;
    name: string;
    role: _Role;
    lastSeen: bigint;
} {
    return {
        id: value.id,
        status: to_candid_Status__1_n45(_uploadFile, _downloadFile, value.status),
        name: value.name,
        role: to_candid_Role_n41(_uploadFile, _downloadFile, value.role),
        lastSeen: value.lastSeen
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageType): {
    text: null;
} | {
    document: null;
} | {
    image: null;
} {
    return value == MessageType.text ? {
        text: null
    } : value == MessageType.document ? {
        document_: null
    } : value == MessageType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    pending: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == Status.pending ? {
        pending: null
    } : value == Status.completed ? {
        completed: null
    } : value == Status.rejected ? {
        rejected: null
    } : value == Status.accepted ? {
        accepted: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    owner: null;
} | {
    worker: null;
} | {
    driver: null;
} {
    return value == Role.owner ? {
        owner: null
    } : value == Role.worker ? {
        worker: null
    } : value == Role.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    offline: null;
} | {
    online: null;
} {
    return value == Status__1.offline ? {
        offline: null
    } : value == Status__1.online ? {
        online: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
